version: "3.8"

networks:
  eclipseworks_network:
    driver: bridge

services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    networks:
      - eclipseworks_network

  database:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eclipseworks@1234
      POSTGRES_DB: eclipseworks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eclipseworks_network

volumes:
  postgres_data:
